meta_product_name: "Hoodi"
meta_title: "Hoodi - Connect with your Neighbourhood"
meta_description: "Cities have become larger and larger. Before neighbours were there to help each other with small daily things. Poeple where able to speak and to share things together; but this has completely disappeared.
                  Hoodi is a new way of connecting Poeple together, especially neighbors. It can easily be described as the wall of your neighbourhood, where Poeple can share informations, ask for favours and creat local events."
meta_image: "Hoodi_Cover_1200x630.png"                       # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"  # required for Twitter Cards
